    const auto psqt = NetworkBridgeAccess::featureTransformer(network).transform(pos,
                                                                                 accumulator_stack,
                                                                                 cache,
                                                                                 transformedFeatures,
                                                                                 bucket);
